<?php

declare(strict_types=1);

namespace ContentBlocks\I18n\Tests\Workbench;

use ContentBlocks\I18n\Tests\Fixtures\Entities;
use PHPUnit\Framework\TestCase;
use Symfony\Bridge\Twig\Extension\RoutingExtension;
use Symfony\Bridge\Twig\Extension\TranslationExtension;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Translation\Translator;
use Twig\Environment;
use Twig\Loader\ArrayLoader;
use Twig\Loader\ChainLoader;
use Twig\Loader\FilesystemLoader;

/**
 * Renders the workbench template directly, to pin the one thing only the markup
 * can answer: **machine translation leaves no trace when no engine is wired.**
 *
 * This package ships no adapter for any translation service — that choice
 * belongs to the host — so "nothing configured" is the default state of a fresh
 * install, not an edge case. It has to look like a workbench without machine
 * translation, not like a broken one: an affordance that can only fail teaches
 * editors to distrust the ones that work.
 */
final class WorkbenchTemplateTest extends TestCase
{
    public function testWithNoEngineWiredNoMachineTranslationAffordanceIsRendered(): void
    {
        $html = $this->render(providers: []);

        // The ⚡ per-field button, the whole-page button, and the engine picker.
        $this->assertStringNotContainsString('data-act="translateField"', $html);
        $this->assertStringNotContainsString('data-act="translateAll"', $html);
        $this->assertStringNotContainsString('data-target="provider"', $html);

        // Everything a translator does by hand is still there.
        $this->assertStringContainsString('data-target="input"', $html);
        $this->assertStringContainsString('data-act="approve"', $html);
        $this->assertStringContainsString('data-act="reset"', $html);
    }

    public function testASingleEngineNeedsNoPickerButGetsItsButtons(): void
    {
        $html = $this->render(providers: [['name' => 'mine', 'label' => 'My engine']]);

        $this->assertStringContainsString('data-act="translateField"', $html);
        $this->assertStringContainsString('data-act="translateAll"', $html);

        // One engine is not a choice: it rides along as a hidden input rather
        // than a one-option dropdown.
        $this->assertStringContainsString('<input type="hidden" data-target="provider" value="mine">', $html);
        $this->assertStringNotContainsString('<select data-target="provider">', $html);
    }

    public function testTwoEnginesGetAPicker(): void
    {
        $html = $this->render(providers: [
            ['name' => 'mine', 'label' => 'My engine'],
            ['name' => 'other', 'label' => 'Other engine'],
        ]);

        $this->assertStringContainsString('<select data-target="provider">', $html);
        $this->assertStringContainsString('<option value="other">Other engine</option>', $html);
    }

    /**
     * Every URL the script calls is generated by the router here, so the routes
     * can be mounted anywhere. A path assembled in JavaScript would survive a
     * remount silently and 404 at runtime.
     */
    public function testEveryEndpointTheScriptCallsIsGeneratedByTheRouter(): void
    {
        $html = $this->render(providers: []);

        foreach ([
            'data-cb-save-url="/mnt/content_blocks_i18n_block_save/1/de"',
            'data-cb-approve-url="/mnt/content_blocks_i18n_block_approve/1/de"',
            'data-cb-translate-url="/mnt/content_blocks_i18n_block_translate/1/de"',
            'data-cb-render-url="/mnt/content_blocks_block_render/1/de"',
            'data-cb-translate-all-url="/mnt/content_blocks_i18n_area_translate/7/de"',
        ] as $attribute) {
            $this->assertStringContainsString($attribute, $html);
        }
    }

    /** A tab title posts to its column routes and has no render route. */
    public function testATabTitleEntryUsesItsColumnRoutes(): void
    {
        $html = $this->render(providers: [['name' => 'mine', 'label' => 'Mine']], extraBlocks: [[
            'kind' => 'column',
            'key' => 'column-4',
            'columnId' => 4,
            'blockLabel' => 'Onglet 1',
            'sectionId' => 10,
            'sectionNumber' => 1,
            'columnNumber' => 1,
            'fields' => [[
                'path' => 'label',
                'pattern' => 'label',
                'label' => 'cb_i18n.workbench.tab_title',
                'labelDomain' => 'content_blocks_i18n',
                'widget' => 'text',
                'source' => 'Détails',
                'value' => null,
                'status' => 'missing',
                'entryIndex' => null,
            ]],
            'progress' => ['locale' => 'de', 'total' => 1, 'translated' => 0, 'outdated' => 0, 'missing' => 1, 'percent' => 0, 'complete' => false],
        ]]);

        $this->assertStringContainsString('data-cb-block="column-4"', $html);
        $this->assertStringContainsString('data-block="column-4"', $html);
        $this->assertStringContainsString('data-cb-save-url="/mnt/content_blocks_i18n_column_save/4/de"', $html);
        $this->assertStringContainsString('data-cb-approve-url="/mnt/content_blocks_i18n_column_approve/4/de"', $html);
        $this->assertStringContainsString('data-cb-translate-url="/mnt/content_blocks_i18n_column_translate/4/de"', $html);
        $this->assertStringContainsString('data-cb-preview-selector="[data-cb-section-id=&quot;10&quot;]"', $html);
        $this->assertSame(1, substr_count($html, 'data-cb-render-url='), 'only the block entry has one');
    }

    /** The arrow is the resolver's URL verbatim, not one derived from preview. */
    public function testTheBackArrowUsesTheResolvedBackUrl(): void
    {
        $html = $this->render(providers: []);

        $this->assertStringContainsString(
            '<a class="cb-wb__back" href="/admin/pages/7/edit"',
            $html,
        );
    }

    public function testNoPublicLinksRenderNoNav(): void
    {
        $this->assertStringNotContainsString('cb-wb__public', $this->render(providers: []));
    }

    public function testEachPublicLinkOpensItsLanguageInANewTab(): void
    {
        $html = $this->render(providers: [], publicLinks: [
            ['code' => 'fr', 'label' => 'Français', 'url' => '/page/7', 'current' => false],
            ['code' => 'de', 'label' => 'Deutsch', 'url' => '/de/page/7', 'current' => true],
        ]);

        $this->assertMatchesRegularExpression(
            '~<a class="cb-wb__public-link"\s+href="/page/7"\s+hreflang="fr"\s+target="_blank"\s+rel="noopener"~',
            $html,
        );
        $this->assertMatchesRegularExpression(
            '~<a class="cb-wb__public-link is-current"\s+href="/de/page/7"\s+hreflang="de"~',
            $html,
        );
        $this->assertStringContainsString('aria-current="true">DE</a>', $html);
    }

    /** A host extends the shipped template and fills only the blocks it needs. */
    public function testAHostFillsTheEmptyBlocks(): void
    {
        $html = $this->render(providers: [], host: <<<'TWIG'
            {% extends '@ContentBlocksI18n/workbench/workbench.html.twig' %}
            {% block cb_wb_head %}<link rel="stylesheet" href="/host.css">{% endblock %}
            {% block cb_wb_topbar_left_end %}<i>host-left-end</i>{% endblock %}
            {% block cb_wb_topbar_right_start %}<i>host-right-start</i>{% endblock %}
            {% block cb_wb_topbar_right_end %}<i>host-right-end-{{ locale }}</i>{% endblock %}
            {% block cb_wb_end %}<i>host-end</i>{% endblock %}
            TWIG);

        $this->assertLessThan(strpos($html, '</head>'), strpos($html, '/host.css'));
        $this->assertLessThan(strpos($html, 'cb-wb__topbar-right'), strpos($html, 'host-left-end'));
        $this->assertLessThan(strpos($html, 'data-act="togglePreview"'), strpos($html, 'host-right-start'));
        $this->assertGreaterThan(strpos($html, 'data-act="togglePreview"'), strpos($html, 'host-right-end-de'));
        $this->assertLessThan(strpos($html, '</header>'), strpos($html, 'host-right-end-de'));
        $this->assertGreaterThan(strpos($html, 'cb-wb__toast'), strpos($html, 'host-end'));
    }

    /**
     * @param list<array{name: string, label: string}> $providers
     * @param list<array<string, mixed>> $publicLinks
     */
    private function render(array $providers, array $publicLinks = [], ?string $host = null, array $extraBlocks = []): string
    {
        $template = '@ContentBlocksI18n/workbench/workbench.html.twig';

        return $this->twig($host)->render($host === null ? $template : 'host.html.twig', [
            'area' => Entities::area(7),
            'locale' => 'de',
            'sourceLocale' => 'fr',
            'localeLabel' => 'Deutsch',
            'sourceLabel' => 'Français',
            'locales' => [
                ['code' => 'fr', 'label' => 'Français', 'source' => true],
                ['code' => 'de', 'label' => 'Deutsch', 'source' => false],
            ],
            'blocks' => [[
                'blockId' => 1,
                'blockType' => 'title',
                'blockLabel' => 'Titre',
                'sectionId' => 10,
                'sectionNumber' => 1,
                'blockNumber' => 1,
                'fields' => [[
                    'path' => 'heading',
                    'pattern' => 'heading',
                    'label' => 'Heading',
                    'labelDomain' => null,
                    'widget' => 'text',
                    'source' => 'Welcome',
                    'value' => null,
                    'status' => 'missing',
                    'entryIndex' => null,
                ]],
                'progress' => ['locale' => 'de', 'total' => 1, 'translated' => 0, 'outdated' => 0, 'missing' => 1, 'percent' => 0, 'complete' => false],
            ], ...$extraBlocks],
            'progress' => ['locale' => 'de', 'total' => 1, 'translated' => 0, 'outdated' => 0, 'missing' => 1, 'percent' => 0, 'complete' => false],
            'previewUrl' => '/page/7?cb_preview=1&cb_chrome=0&cb_locale=de',
            'backUrl' => '/admin/pages/7/edit',
            'publicLinks' => $publicLinks,
            'providers' => $providers,
            'csrfToken' => 'tok',
        ]);
    }

    private function twig(?string $host = null): Environment
    {
        $files = new FilesystemLoader();
        $files->addPath(__DIR__ . '/../../templates', 'ContentBlocksI18n');
        $loader = new ChainLoader([new ArrayLoader(['host.html.twig' => $host ?? '']), $files]);

        // strict_variables: a template that reads a key the controller stopped
        // passing should fail here rather than render a silent blank.
        $twig = new Environment($loader, ['strict_variables' => true]);

        // Route name + parameters, spelled out in the output, so the assertions
        // above read as "which route", not "which path".
        $urls = $this->createMock(UrlGeneratorInterface::class);
        $urls->method('generate')->willReturnCallback(
            static fn (string $route, array $params = []): string => '/mnt/' . $route
                . ($params === [] ? '' : '/' . implode('/', $params)),
        );

        $twig->addExtension(new RoutingExtension($urls));
        $twig->addExtension(new TranslationExtension(new Translator('en')));

        $stack = new RequestStack();
        $stack->push(new Request());
        $app = new \Symfony\Bridge\Twig\AppVariable();
        $app->setRequestStack($stack);
        $twig->addGlobal('app', $app);

        return $twig;
    }
}
