<?php

declare(strict_types=1);

namespace ContentBlocks\I18n\Tests\Workbench;

use ContentBlocks\I18n\Tests\Fixtures\Entities;
use PHPUnit\Framework\TestCase;
use Symfony\Bridge\Twig\Extension\RoutingExtension;
use Symfony\Bridge\Twig\Extension\TranslationExtension;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Translation\Translator;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

/**
 * Renders the workbench template directly, to pin the one thing only the markup
 * can answer: **machine translation leaves no trace when no engine is wired.**
 *
 * This package ships no adapter for any translation service — that choice
 * belongs to the host — so "nothing configured" is the default state of a fresh
 * install, not an edge case. It has to look like a workbench without machine
 * translation, not like a broken one: an affordance that can only fail teaches
 * editors to distrust the ones that work.
 */
final class WorkbenchTemplateTest extends TestCase
{
    public function testWithNoEngineWiredNoMachineTranslationAffordanceIsRendered(): void
    {
        $html = $this->render(providers: []);

        // The ⚡ per-field button, the whole-page button, and the engine picker.
        $this->assertStringNotContainsString('data-act="translateField"', $html);
        $this->assertStringNotContainsString('data-act="translateAll"', $html);
        $this->assertStringNotContainsString('data-target="provider"', $html);

        // Everything a translator does by hand is still there.
        $this->assertStringContainsString('data-target="input"', $html);
        $this->assertStringContainsString('data-act="approve"', $html);
        $this->assertStringContainsString('data-act="reset"', $html);
    }

    public function testASingleEngineNeedsNoPickerButGetsItsButtons(): void
    {
        $html = $this->render(providers: [['name' => 'mine', 'label' => 'My engine']]);

        $this->assertStringContainsString('data-act="translateField"', $html);
        $this->assertStringContainsString('data-act="translateAll"', $html);

        // One engine is not a choice: it rides along as a hidden input rather
        // than a one-option dropdown.
        $this->assertStringContainsString('<input type="hidden" data-target="provider" value="mine">', $html);
        $this->assertStringNotContainsString('<select data-target="provider">', $html);
    }

    public function testTwoEnginesGetAPicker(): void
    {
        $html = $this->render(providers: [
            ['name' => 'mine', 'label' => 'My engine'],
            ['name' => 'other', 'label' => 'Other engine'],
        ]);

        $this->assertStringContainsString('<select data-target="provider">', $html);
        $this->assertStringContainsString('<option value="other">Other engine</option>', $html);
    }

    /**
     * Every URL the script calls is generated by the router here, so the routes
     * can be mounted anywhere. A path assembled in JavaScript would survive a
     * remount silently and 404 at runtime.
     */
    public function testEveryEndpointTheScriptCallsIsGeneratedByTheRouter(): void
    {
        $html = $this->render(providers: []);

        foreach ([
            'data-cb-save-url="/mnt/content_blocks_i18n_block_save/1/de"',
            'data-cb-approve-url="/mnt/content_blocks_i18n_block_approve/1/de"',
            'data-cb-translate-url="/mnt/content_blocks_i18n_block_translate/1/de"',
            'data-cb-render-url="/mnt/content_blocks_block_render/1/de"',
            'data-cb-translate-all-url="/mnt/content_blocks_i18n_area_translate/7/de"',
        ] as $attribute) {
            $this->assertStringContainsString($attribute, $html);
        }
    }

    /**
     * @param list<array{name: string, label: string}> $providers
     */
    private function render(array $providers): string
    {
        return $this->twig()->render('@ContentBlocksI18n/workbench/workbench.html.twig', [
            'area' => Entities::area(7),
            'locale' => 'de',
            'sourceLocale' => 'fr',
            'localeLabel' => 'Deutsch',
            'sourceLabel' => 'Français',
            'locales' => [
                ['code' => 'fr', 'label' => 'Français', 'source' => true],
                ['code' => 'de', 'label' => 'Deutsch', 'source' => false],
            ],
            'blocks' => [[
                'blockId' => 1,
                'blockType' => 'title',
                'blockLabel' => 'Titre',
                'sectionId' => 10,
                'sectionNumber' => 1,
                'blockNumber' => 1,
                'fields' => [[
                    'path' => 'heading',
                    'pattern' => 'heading',
                    'label' => 'Heading',
                    'labelDomain' => null,
                    'widget' => 'text',
                    'source' => 'Welcome',
                    'value' => null,
                    'status' => 'missing',
                    'entryIndex' => null,
                ]],
                'progress' => ['locale' => 'de', 'total' => 1, 'translated' => 0, 'outdated' => 0, 'missing' => 1, 'percent' => 0, 'complete' => false],
            ]],
            'progress' => ['locale' => 'de', 'total' => 1, 'translated' => 0, 'outdated' => 0, 'missing' => 1, 'percent' => 0, 'complete' => false],
            'previewUrl' => '/page/7?cb_preview=1&cb_chrome=0&cb_locale=de',
            'providers' => $providers,
            'csrfToken' => 'tok',
        ]);
    }

    private function twig(): Environment
    {
        $loader = new FilesystemLoader();
        $loader->addPath(__DIR__ . '/../../templates', 'ContentBlocksI18n');

        // strict_variables: a template that reads a key the controller stopped
        // passing should fail here rather than render a silent blank.
        $twig = new Environment($loader, ['strict_variables' => true]);

        // Route name + parameters, spelled out in the output, so the assertions
        // above read as "which route", not "which path".
        $urls = $this->createMock(UrlGeneratorInterface::class);
        $urls->method('generate')->willReturnCallback(
            static fn (string $route, array $params = []): string => '/mnt/' . $route
                . ($params === [] ? '' : '/' . implode('/', $params)),
        );

        $twig->addExtension(new RoutingExtension($urls));
        $twig->addExtension(new TranslationExtension(new Translator('en')));

        $stack = new RequestStack();
        $stack->push(new Request());
        $app = new \Symfony\Bridge\Twig\AppVariable();
        $app->setRequestStack($stack);
        $twig->addGlobal('app', $app);

        return $twig;
    }
}
